# Generated by Django 4.2.1 on 2024-03-29 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.IntegerField(verbose_name='Координата X')),
                ('y_coordinate', models.IntegerField(verbose_name='Координата Y')),
                ('is_entry', models.BooleanField(default=False, verbose_name='Вход')),
                ('is_exit', models.BooleanField(default=False, verbose_name='Выход')),
            ],
            options={
                'verbose_name': 'Клетка',
                'verbose_name_plural': 'Клетки',
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_cell_1', to='main.cell', verbose_name='Клетка 1')),
                ('cell_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wall_cell_2', to='main.cell', verbose_name='Клетка 2')),
            ],
            options={
                'verbose_name': 'Стена',
                'verbose_name_plural': 'Стены',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cell', verbose_name='Текущая клетка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код комнаты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватная')),
                ('current_turn_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_turn', to='main.player', verbose_name='Текущий ход игрока')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player_1', to='main.player', verbose_name='Игрок 1')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player_2', to='main.player', verbose_name='Игрок 2')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
