# Generated by Django 4.2.1 on 2024-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtranslation',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='achievementtranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ranktranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
