# Generated by Django 4.2.1 on 2024-04-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_achievementtranslation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rating_for_player_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating_for_player_2',
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Рейтинговая игра'), (1, 'Игра на деньги')], default=0, verbose_name='Тип игры'),
        ),
    ]
