# Generated by Django 4.2.1 on 2024-04-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_game_rating_for_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, to='main.achievement'),
        ),
    ]
