# Generated by Django 4.2.1 on 2024-04-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_turn_player',
        ),
        migrations.AddField(
            model_name='player',
            name='current_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Код комнаты'),
        ),
    ]
