# Generated by Django 4.2.1 on 2024-04-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_game_player_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ставка'),
        ),
    ]
