# Generated by Django 3.2.16 on 2024-07-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_game_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_stage',
            field=models.IntegerField(default=1, verbose_name='Стадия игры'),
        ),
    ]
