# Generated by Django 3.2.16 on 2024-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_game_game_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ready_players',
            field=models.IntegerField(default=0),
        ),
    ]
