# Generated by Django 4.1.13 on 2024-08-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_game_player_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='can_spectate',
            field=models.BooleanField(default=True, verbose_name='Можно ли наблюдать за игрой'),
        ),
    ]
