# Generated by Django 4.1.13 on 2024-08-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_game_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='can_spectate',
        ),
    ]
