# Generated by Django 4.1.13 on 2024-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_game_can_spectate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.TextField(default='', verbose_name='ник победителя'),
        ),
    ]
