# Generated by Django 4.1.13 on 2024-08-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя'),
        ),
    ]
