# Generated by Django 4.1.13 on 2024-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
